UserRegistrationAssignment_V1/ViewModels/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UserRegistrationAssignment_V1.ViewModels
{
    public class ChangePassword
    {
        public class UserLogin
        {
            [Required]
            [Display(Name = "Email")]
            [EmailAddress]
            public string EmailId { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Required(ErrorMessage = "You must provide a password")]
            [DataType(DataType.Password)]
            [Display(Name = "New Password")]
            public string NewPassword { get; set; }

            [Required(ErrorMessage = "You must provide the same password")]
            [DataType(DataType.Password)]
            [Compare("NewPassword", ErrorMessage = "The password and confirmation password do not match.")]
            [Display(Name = "Confirm New Password")]
            public string ConfirmPassword { get; set; }
        }
    }
}

UserRegistrationAssignment_V1/ViewModels/UserLogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UserRegistrationAssignment_V1.ViewModels
{
    public class UserLogin
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string EmailId { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

UserRegistrationAssignment_V1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserRegistrationAssignment_V1.ViewModels;
using UserRegistrationAssignment_V1.UserModelContext;

namespace UserRegistrationAssignment_V1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult UserLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UserLogin(UserLogin userLogin)
        {
            if (!ModelState.IsValid)
            {
                return View(userLogin);
            }
            using (UserAccountContext obj=new UserAccountContext())
            {
                string pass = PasswordClass.Encrypt(userLogin.Password);
                var userData = obj.UserDetails.FirstOrDefault(x => x.Email == userLogin.EmailId && x.Password == pass);
                if (userData != null)
                {
                    Session["email"] = userLogin.EmailId;
                    Session["password"] = pass;
                    ViewBag.message = "Login successful";
                    return RedirectToAction("Details", "Home");
                }
                else
                {
                    ViewBag.message = "Invalid email or password";
                }
            }
            return View();
        }
        public ActionResult UserLogout()
        {
            Session["email"] = null;
            Session["password"] = null;
            return RedirectToAction("UserLogin");
        }
        public ActionResult ChangePassword()
        {
            return View();
        }

    }
}

UserRegistrationAssignment_V1/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserRegistrationAssignment_V1.ViewModels;
using UserRegistrationAssignment_V1.Models;
using UserRegistrationAssignment_V1.UserModelContext;
using UserRegistrationAssignment_V1.BAL;
using System.Net.Mail;
using System.Net;
using System.Xml.Linq;

namespace UserRegistrationAssignment_V1.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        public ActionResult Register()
        {
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Register(UserRegistration userAccount)
        {
            string message = "";
            bool status = false;
            if (!ModelState.IsValid)
            {
                return View(userAccount);
            }
            using (UserAccountContext userDB = new UserAccountContext())
            {
                var userExist = userDB.UserDetails.FirstOrDefault(x => x.Email == userAccount.EmailId);
                if (userExist != null)
                {
                    ViewBag.invalidEmailmMessage = "Email id is already Exit";
                    return View(userAccount);
                }
                BusnissesLogics.ContactTypeIsEmpty(userDB);
                
                var uploadDir = "~/Images";
                var fileName = userAccount.EmailId + userAccount.ImageUpload.FileName;
                var imagePath = Path.Combine(Server.MapPath(uploadDir), fileName);
                var imageUrl = Path.Combine(uploadDir, fileName);
                userAccount.ImageUpload.SaveAs(imagePath);

                User userModel=BusnissesLogics.UploadUserData( userDB,  userAccount, imageUrl);
                BusnissesLogics.UploadUserContactData(userDB, userAccount, userModel);
                SendVarificationCode(userModel.Email, userModel.ActivationCode.ToString());
                message = "Registered successfully done . Account Activation link "+
                    "has been sent to your email id:"+userModel.Email;
                status = true;
                ModelState.Clear();

                 ViewBag.successMessage = message;
                ViewBag.status = status;

            }
            return View(userAccount);
        }
        [NonAction]
        public void SendVarificationCode(string emailId, string activationCode)
        {
            var verifyUrl = "/Login/UserLogin" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);
            var fromEmail = new MailAddress("mindfiresolutionspurnendu@gmail.com","DotNet MVC");
            var toEmail = new MailAddress(emailId);
            var fromEmailPassword = "mindfire@123";
            string subject = "Your account is successfully created";
            string body = "<br/><br/>We are excited to tell you that your MVC account is"+
                "successfully created . Please click on below link to verify your account"+
                "<br/><br/><a href = '" + link+"'>"+link+"</a>";
            var smtp = new SmtpClient
            {
                  Host = "smtp.gmail.com",
                  Port = 587,
                  EnableSsl =true,
                  DeliveryMethod = SmtpDeliveryMethod.Network,
                  UseDefaultCredentials = false,
                  Credentials = new NetworkCredential(fromEmail.Address,fromEmailPassword)
            };
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }
    }
}

UserRegistrationAssignment_V1/Views/Login/ForgotPassword.cshtml
@model UserRegistrationAssignment_V1.ViewModels.PasswordReset
@using UserRegistrationAssignment_V1.ViewModels
@{
    ViewBag.Title = "ForgotPassword";
}

<h2>Forgot Password</h2>
@using (Html.BeginForm("ForgotPassword", "Login", FormMethod.Post, new { @class = "registration", role = "form" }))
{
        @Html.LabelFor(m => m.EmailId)
        @Html.TextBoxFor(m => m.EmailId, new { placeholder = "Enter Your Email" })
        <span class="invalid-input">@Html.ValidationMessageFor(m => m.EmailId)</span>
        <span class="invalid-input">@ViewBag.invalidEmailmMessage</span>

        <div>
            <button type="submit" value="Submit" id="SendCodeButton">Get Reset Link</button>
        </div>
}

UserRegistrationAssignment_V1/Views/Login/UserLogin.cshtml
@model UserRegistrationAssignment_V1.ViewModels.UserLogin
@{
    ViewBag.Title = "Login";
}
<h3>Login</h3>

@using (Html.BeginForm("UserLogin", "Login", FormMethod.Post, new { @class = "registration", role = "form" }))
{
    @Html.LabelFor(m => m.EmailId)
    @Html.TextBoxFor(m => m.EmailId, new { @placeholder = "Enter Your Email" })
    <span class="invalid-input">@Html.ValidationMessageFor(m => m.EmailId)</span>

    @Html.LabelFor(m => m.Password)
    @Html.PasswordFor(m => m.Password, new { @placeholder = "Enter Your Password" })
    <span class="invalid-input">@Html.ValidationMessageFor(m => m.Password)</span>
    <div>
        <button type="submit" value="Submit" id="LoginButton">Log in</button>
    </div>
}

<div class="registration">
    <span class="have-account">Don't have an account? @Html.ActionLink("  Register", "Register", "Registration") here</span>
</div>
<div class="registration">
    <span class="have-account">@Html.ActionLink("Forgot Password", "ForgotPassword", "Login")</span>
</div>